### ISSUE TITLE
Check Default Types

### ISSUE THREAD

**Issue by cpageler93** [cpageler93/RAML-Swift#12]
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#determine-default-types

**Comment by cpageler93** [comment]
Missing Defaults for:

```yaml
body:
  application/json:
    # default type is `any`
```

```yaml
body:
  # default type is `any`
```
