### ISSUE TITLE
Allow Decimals as values 

### ISSUE THREAD

**Issue by cpageler93** [cpageler93/RAML-Swift#37]
```yaml
#%RAML 1.0
title: Illustrate query parameter variations
types:
  lat-long:
    properties:
      lat: number
      long: number
  loc:
    properties:
      location:
  paging:
    properties:
      start?: number
      page-size?: number
/locations:
  get:
    queryString:
      type: [paging, lat-long | loc ]
      examples:
        first:
          value:
            start: 2
            lat: 12
            long: 13
        second:
          value:
            start: 2
            page-size: 20
            location: 1,2
        third:
          value:
            lat: 12
            location: 2
          strict: false
```
